### ISSUE TITLE
Wrap code to 80 columns

### ISSUE THREAD

**Issue by FiniteReality** [FiniteReality/disccord#48]
All future code should be wrapped to 80 columns (including line terminators: we use line-feeds, so that means 79 columns available for code).

This is to make the code easier to read on a single screen without having to scroll horizontally.

**Comment by edosedgar** [comment]
Assign this task to me, I am in progress

**Comment by FiniteReality** [comment]
Will do - Github won't let me assign it in the UI though so I'll just have to remember that you're working on it.

**Comment by edosedgar** [comment]
Could you mark this issue as a resolved by me?

**Comment by FiniteReality** [comment]
Yep, I forgot to when I accepted the PR. Whoops.
