### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by FiniteReality** [FiniteReality/disccord#5]
This issue will be used to track the status of the REST API.

- [x] `GET /gateway`

**Comment by abuneri** [comment]
Below are end points that still need to be fully wrapped:

- [x] `POST /channels/{channel.id}/messages` (**needs file implementation**)

- [x] `PATCH /users/@me`
- [x] `PATCH /guilds/{guild.id}/members/@me/nick`

- [x] `GET /guilds/{guild.id}/prune`

- [x] `POST /guilds/{guild.id}/prune`

- [x] `GET /guilds/{guild.id}/regions`

**Comment by sedruk** [comment]
once https://github.com/FiniteReality/disccord/pull/27 is merged this issue can be closed

**Comment by FiniteReality** [comment]
As of 659f676, all REST endpoints have been wrapped. If Discord makes changes to their REST api in the future, please create new issues for each affected endpoint.
